[pytest]
pythonpath = .
addopts =
    -v
    --alluredir=allure-results
    --clean-alluredir
    --reruns=1
    --reruns-delay=2
testpaths = tests
markers =
    smoke: quick sanity checks
    regression: full regression suite
    negative: negative scenarios
